spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pas
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml